#!/bin/bash

[[ `whoami` == 'root' ]]\
  && echo "don't run as root."\
  && exit 1

[[ -d '${HOME}/.zinit' ]]\
  && echo ".zinit/ already exists, skipping."\
  && exit 2

(
  cd ${HOME} &&\
  sh -c "$(curl --tlsv1.3 -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
)
