#!/bin/bash
[[ `whoami` == 'root' ]] && { echo "never run Rofi as root"; exit 1; } # bad pid file permissions

function _help() {
  cat << EOF
Usage `basename $0` [OPTION]

OPTIONS
  -e, --emacs     an Emacs style launcher

EOF
}

# note: we need -normal-window for AwesomeWM to recognise as a client
case "$1" in
  "-e"|"--emacs") rofi -dmenu -normal-window -pid /tmp/rofi.pid;;
  "-h"|"--help") _help;;
  *) _help && exit 1;;
esac
