#!/bin/bash

function parse() {
  find "${HOME}/org" -name '*.org' -type f -exec cat '{}' \;
}

function count() {
  wc --lines --words --chars
}

function format() {
  # $1 is the heading
  echo -e "${1}:"
  awk '{print "  lines:\t" $1 "\n  words:\t" $2 "\n  chars:\t" $3}'
}

parse | count | format "STATS FOR NOTES"
