#!/bin/bash
# DEPS (fedora packages):
# - words: for gen_username()

# Check if the script is being run by root
if [ "$EUID" -eq 0 ]; then
  echo "This script should not be run as root"
  exit 1
fi

# Help menu
help_menu() {
  cat << EOF
Usage: $(basename $0) [OPTION]...

Options:
  h,-h,help,--help   Display this help menu.
  p,pass             Get a password.
  u,user             Get a username.
  t,totp             Get a TOTP.

EOF
}

# our working directory for everything
mkdir -p "${HOME}/secrets"
cd "${HOME}/secrets"

# Find a all directories with $1 file
function find_dirs_with() {
  fd -t f "$1" -x dirname {}
}

# Pick from a set of inputs; $1 (if provided) is appended to the result.
# Often you want to show results without the noise of the full path
# (including the file name), so this will display without, and append
# afterwards: e.g.   echo foo | pick "foo" will display ./ but return ./foo
function pick() {
  local result=$(fzf)
  if [ -z "$result" ]; then
    echo "no selection made"
    exit 1
  fi
  [[ -n "$1" ]] && echo "${result}/$1" || echo "$result"
}

# Copy to clipboard; $1 is a simple string to provide context to the message
function copy() {
  tr -d '[:space:]' | xclip -selection clipboard
  echo "$1 copied!"
}

# Grab an item from a file -- e.g. pass:<<THIS>>; $1 is the line 'name' (e.g. 'pass').
function item() {
  xargs grep "$1" | cut -d: -f2 | tr -d '[:space:]'
}

# Generate a TOTP. It uses the key and optional outlen keys from the provided file:
#   key:ABC...
#   outlen:6
# Outlet dictates the output length of the OTP. If not specified, it defaults to 6.
function totp() {
  read -r path
  local len=`echo "$path" | item "outlen"`
  oathtool --totp -b -d ${len:-6} "`echo $path | item 'key'`"
}

# Function to select directory with FZF.
select_directory() {
  local result=$(ls -d "${HOME}/secrets"/* | fzf)
  if [ -z "$result" ]; then
    echo "no selection made"
    exit 1
  fi
  echo "$result"
}

# Function to grep credentials
grep_creds() {
  local P=$(select_directory)
  if ! grep -q "$1" "${P}/creds"; then
    echo "$1 doesn't exist in ${P}/creds"
    exit 1
  fi
  grep "$1" "${P}/creds" | cut -d: -f2- | tr -d '[:space:]' | xclip -selection clipboard
  echo "$1 copied"
}

# Check if no arguments were passed
if [ $# -eq 0 ]; then
  help_menu
  exit 1
fi

# gen_username() {
#   pwgen $((RANDOM%5+8)) 1
# }

# Generate a username from /usr/share/dict/words (provided by the 'words' package.
# It creates <12 in len username: one or two words, lowercase, no hyphens, appended
# with a number 1-99: e.g. foobar27.
# The user selects y/n to ceate a list of candidates, then chooses one after finishing.
# This function echos the result: a single username.
gen_username() {
  local temp_file=$(mktemp)  # holds candidates
  trap "rm -f '$temp_file'" EXIT

  echo "---------------------------------------------"
  echo "Add word to candidates? [y]es, [n]o, [f]inish"
  echo "---------------------------------------------"
  while true; do
    # pick one or two words
    local word1=$(grep -v -w '.*-.*' /usr/share/dict/words | shuf -n 1)
    local word2=$(grep -v -w '.*-.*' /usr/share/dict/words | shuf -n 1)
    local combined="${word1}${word2}"
    if [ ${#combined} -gt 10 ]; then
      word_candidate=$word1
    else
      word_candidate=$combined
    fi

    # append a number, and set lowercase
    local random_number=$(( $RANDOM % 99 + 1 ))
    word_candidate+=$random_number
    word_candidate=${word_candidate,,}

    echo "  $word_candidate? [y/n/f]"
    read -sn 1 answer

    # save candidate or finish
    if [[ "$answer" == "y" ]]; then
      echo $word_candidate >> "$temp_file"
    elif [[ "$answer" == "f" ]]; then
      break
    fi
  done

  # select one candidate
  selected_word=$(fzf +s --tiebreak=index --tac < "$temp_file")
  [[ -z "$selected_word" ]] && echo "no selection made; exiting" && exit 1
  echo "$selected_word"
}

gen_username
exit
# Route arguments via a switch
case "$1" in
  p|pass) grep_creds "pass";;
  u|user) grep_creds "user";;
  t|totp) find_dirs_with "totp" | pick "totp" | totp | copy "key";;
  h|help|-h|--help) help_menu;;
  *) echo "Invalid option: $1"
     help_menu
     exit 1
     ;;
esac
