#!/bin/bash
set -e

# Check if the script is being run by root
if [ "$EUID" -eq 0 ]; then 
  echo "This script should not be run as root"
  exit 1
fi

# Help menu
help_menu() {
  cat << EOF
Usage: $0 [OPTION]...

Options:
 -p, p, pass, --pass, pw Append "creds" to the value of P
 -u, u, --user, user Append "creds" to the value of P and grep for "user"
 -h, --help, help, h Display this help menu

EOF
}

# Function to select directory with FZF
select_directory() {
  local result=$(ls -d "${HOME}/secrets"/* | fzf)
  if [ -z "$result" ]; then
    echo "no selection made"
    exit 1
  fi
  echo "$result"
}

# Function to grep credentials
grep_creds() {
  local P=$(select_directory)
  if ! grep -q "$1" "${P}/creds"; then
    echo "$1 doesn't exist in ${P}/creds"
    exit 1
  fi
  grep "$1" "${P}/creds" | cut -d: -f2- | tr -d '[:space:]' | xclip -selection clipboard
  echo "$1 copied"
}

# Check if no arguments were passed
if [ $# -eq 0 ]; then
  help_menu
  exit 1
fi

# Route arguments via a switch
case "$1" in
  -p|p|pass|--pass|pw) grep_creds "pass";;
  -u|u|--user|user) grep_creds "user";;
  -h|--help|help|h) help_menu;;
  *) echo "Invalid option: $1"
     help_menu
     exit 1
     ;;
esac

