#!/bin/env python3
from subprocess import check_output
import sys
from ipaddress import ip_address


def listify(byts):
    return byts.decode('utf-8').split()


def is_ip(target):
    try:
        ip_address(target)
    except ValueError:
        return False
    return True


def filter_ips(hosts):
    return list(filter(is_ip, hosts))


def dig_short(domain):
    return listify(check_output(f'dig +short {domain}', shell=True))


def dig_long(domain):
    return listify(check_output(f'dig {domain}', shell=True))


def host_info(target):
    ips = [target] if is_ip(target) else filter_ips(dig_short(target))
    for ip in ips:
        yield check_output(f"curl --silent https://ipinfo.io/{ip}", shell=True).decode("utf-8")


def display_info(targets):
    reset="\033[0m"
    bold="\033[1m"
    for t in targets:
        print(f"{bold}{t}{reset}:")
        for info in host_info(t):
            print(f"{info}\n")


display_info(sys.argv[1:])
