#!/bin/bash

SIZE=30
ROOT="/usr/local/scripts/dmenu-scripts"

function cmds() {
  # display available  commands
  local names=`find "$ROOT" -exec sh -c 'echo $(basename {})' \;`

  echo "$names" | sort | launcher
}

function ctx() {
  # a context aware second menu, that matches against the command.
  case "$1" in
    "shutdown"|"kill"|"pause")
      qvm-ls --running --raw-list
      ;;
    "start")
      qvm-ls --halted --raw-list
      ;;
    "unpause")
      qvm-ls --paused --raw-list
      ;;
    *)
      # keep this as /any/ domain
      qvm-ls --raw-list
      ;;
  esac
}

function defaults() {
  # define default domains for cmds
  # cases are script names, echo the domain name.
  case "$1" in 
    "emacs"|"notes")
      echo "dev";
      ;;
    "vpnlog")
      echo "vpn";
      ;;
    "youtube"|"rss")
      echo "untrusted";
      ;;
    "irc")
      echo "irc";
      ;;
    "sync"|"qube-manager"|"pavucontrol")
      echo "dom0";
      ;;
  esac
}

# first select the desired command
cmd=`cmds`
[[ -z "$cmd" ]] && exit 0;

# check if it has a default domain
default=`defaults "$cmd"`

if [[ "$default" == "dom0" ]]; then
  sh "$ROOT/$cmd" &
  exit 0;
elif [[ -n "$default" ]]; then
  # use default domain if it has one
  domain="$default";
else
  # otherwise display context menu to select one
  context=`ctx "$cmd"`
  [[ -z "$context" ]] && exit 0;
  domain=`echo -e "$context" | launcher`
  [[ -z "$domain" ]] && exit 0;
fi

[[ -z "$ROOT" || -z "$cmd" || -z "$domain" ]] && notify-send "null arg for launcher" && exit 1;

sh "$ROOT/$cmd" "$domain" &
